title: This sprite needs you
hero_image: images/banner.png
description: Create a virtual pet, character, or nature simulation that the user can interact with to help it.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Your idea
  - title: Build and test
    completion: engaged
  - title: Share
    completion: internal
  - title: Reflect
  - title: Upgrade your project
    completion: external
  - title: What next?
