---
title: このスプライトにはあなたが必要だ
hero_image: images/banner.png
description:
  - あなたが触れ合って助けてあげることができる仮想のペット、キャラクター、自然のシミュレーションを作りましょう
  - それを助けるために対話します
meta_title: 子供とティーンエイジャーのためのScratchコーディングプロジェクト｜このスプライトにはあなたが必要です
meta_description: Raspberry Pi Foundationが提供するキッズ＆ティーン向けのコーディング・プロジェクトで、Scratchによるコーディングを学びましょう。Scratchで触れ合えるバーチャルペットを作ろう。
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: はじめに
  - 
    title: あなたのアイデア
  - 
    title: 作って試す
    completion:
      - engaged
      - internal
  - 
    title: チェックリスト
    completion:
      - external
  - 
    title: プロジェクトをアップグレードする
  - 
    title: 共有
  - 
    title: 次は何をしましょうか？
