---
title: Mae'r corlun hwn dy angen di
hero_image: images/banner.png
description:
  - Creu anifail anwes rhithwir, cymeriad, neu efelychiad o fyd natur y gall y defnyddiwr ryngweithio ag ef i'w helpu.
  - interact with to help it.
meta_title: Scratch coding projects for kids and teens | This sprite needs you
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a virtual pet you can interact with in Scratch.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Byddi di'n creu
  - 
    title: Dy syniad
  - 
    title: Adeiladu a phrofi
    completion:
      - engaged
      - internal
  - 
    title: Rhestr wirio
    completion:
      - external
  - 
    title: Uwchraddio dy brosiect
    challenge: true
  - 
    title: Rhannu
  - 
    title: Beth nesaf?
