---
title: Tato postava tě potřebuje
hero_image: images/banner.png
description:
  - Vytvoř si virtuálního mazlíčka, postavu nebo simulaci přírody, se kterou může uživatel
  - interagovat a pomoci jim.
meta_title: Kódovací projekty ve Scratchi pro děti a náctileté | Tato postava tě potřebuje
meta_description: Nauč se kódovat ve Scratch s projekty Raspberry Pi Foundation pro děti a dospívající. Vytvoř si virtuálního mazlíčka, se kterým můžeš ve Scratchi interagovat.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Co budeš dělat
  - 
    title: Tvůj nápad
  - 
    title: Vytoř a testuj
    completion:
      - engaged
      - internal
  - 
    title: Seznam
    completion:
      - external
  - 
    title: Vylepši si projekt
  - 
    title: Sdílej
  - 
    title: Co dál?
