---
title: Este objeto te necesita
hero_image: images/banner.png
description:
  - Crea una mascota virtual, un personaje o una simulación de la naturaleza con la que el usuario pueda
  - interactuar con para ayudarlo.
meta_title: Proyectos de codificación de Scratch para niños y adolescentes | Este objeto te necesita
meta_description: Aprende a codificar en Scratch con los proyectos de codificación de la Fundación Raspberry Pi para niños y adolescentes. Haz una mascota virtual con la que puedas interactuar en Scratch.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Lo que harás
  - 
    title: Tu idea
  - 
    title: Construye y prueba
    completion:
      - engaged
      - internal
  - 
    title: Lista de control
    completion:
      - external
  - 
    title: Mejora tu proyecto
    challenge: true
  - 
    title: Comparte
  - 
    title: '¿Qué sigue?'
