---
title: Ce sprite a besoin de toi
hero_image: images/banner.png
description:
  - Create a virtual pet, character, or nature simulation that the user can
  - interact with to help it.
meta_title: Scratch coding projects for kids and teens | This sprite needs you
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a virtual pet you can interact with in Scratch.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Introduction
  - 
    title: Ton idée
  - 
    title: Construire et tester
    completion:
      - engaged
      - internal
  - 
    title: Liste de contrôle
    completion:
      - external
  - 
    title: Améliorer ton projet
    challenge: true
  - 
    title: Partager
  - 
    title: Et ensuite ?
