---
title: Ce sprite a besoin de toi
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: Ton idée
  - 
    title: Construire et tester
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Partager
  - 
    title: Et ensuite ?
